Tuned Launcher :)
Manchester-Central/2022-Rapid-React pull request #146
Opened 2022-05-25 00:28 UTC by TriNVu

2022-05-25 04:25 UTC, jnallard requested changes

2022-05-25 04:25 UTC, jnallard commented on src/main/java/frc/robot/Robot.java
> +  public static final boolean IsDebuggingMode = true;
@TriNVu We should revert this before merging

2022-05-25 04:25 UTC, jnallard commented on src/main/java/frc/robot/subsystems/Launcher.java
> +    double velocityF = 0.055; // k_f = (PERCENT_POWER X 1023) / OBSERVED_VELOCITY 0.023
We can remove the commented values too

2022-06-02 22:32 UTC, Kjenneth-Obrice approved these changes
Josh and I reviewed this together.

2022-06-02 22:33 UTC, jnallard approved these changes

2022-06-02 22:33 UTC, merged